### ISSUE TITLE
Searx: Change invidious instance to new domain

### ISSUE THREAD

**Issue by 89Q12** [TheKitty-zone/k3s-infra#2]
Currently the instance searx has configured is still the old domain but migration to new domain is almost complete so this is missing.
Solution, change Invidious instance url in:
deployments/searx/values.yml

**Comment by AndromedaCLI** [comment]
Closed by https://github.com/TheKitty-zone/k3s-infra/commit/556f08f7b5ad1852fdca758f6a66d8fff92cf966
